// client/src/pages/legal/RefundPolicy.jsx
import React from 'react';
import LegalLayout from './LegalLayout';

export default function RefundPolicy() {
  return (
    <LegalLayout title="Cancellation & Refund Policy" lastUpdated="October 2026">
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">1. Nature of Digital Services</h2>
        <p>
          BrandVox AI provides compute credits for on-demand cloud artificial intelligence video rendering, motion transfer, and image synthesis. Due to the high real-time cloud GPU costs associated with neural network inference, our refund policy balances consumer fairness with compute overheads.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">2. Automatic In-App Credit Protection</h2>
        <div className="bg-[#1A1A1A] border border-primary/30 rounded-xl p-5 space-y-2">
          <h3 className="font-bold text-white text-base flex items-center space-x-2">
            <span>⚡ Automated Generation Failure Protection</span>
          </h3>
          <p className="text-xs text-white/70 leading-relaxed">
            If any video or image generation job dispatched through BrandVox AI encounters an internal error, cloud provider timeout, or pipeline failure, <strong>the exact credit balance deducted for that job is immediately and automatically refunded back to your account balance</strong>. You are never billed for failed technical runs.
          </p>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">3. Credit Top-Up Packages & Fiat Currency Refunds</h2>
        <p>
          Credit top-up packages purchased via UPI or approved payment aggregators are delivered immediately upon manual or automated transaction verification:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-white/70">
          <li><strong>Unused Packages:</strong> If you purchase a credit package and have not consumed any of the newly acquired credits, you may request a full refund to your original source account within <strong>48 hours</strong> of payment.</li>
          <li><strong>Partially Used Packages:</strong> Once credits from a purchased package have been consumed for completed generations, the monetary value of that package is strictly non-refundable due to consumed third-party GPU compute.</li>
          <li><strong>Duplicate Charges:</strong> In the event of a verified accidental duplicate UPI debit for the same order reference, the duplicate amount will be refunded in full within 5–7 business days upon receipt of bank statement proof.</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">4. UPI UTR Reconciliation & Disputes</h2>
        <p>
          For manual UPI transfers, credits are approved based on the 12-digit UTR reference number generated by your banking app (Google Pay, PhonePe, Paytm, BHIM, Cred). If you experience a delay in credit credit allocation:
        </p>
        <ol className="list-decimal pl-5 space-y-2 text-white/70">
          <li>Verify your 12-digit UTR number in your transaction history tab on the Credits page.</li>
          <li>Email our support team with your registered email and payment screenshot.</li>
          <li>Our billing team will reconcile with banking records within 24 hours.</li>
        </ol>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">5. How to Initiate a Refund or Billing Inquiry</h2>
        <p>
          To submit a refund request or report a billing dispute, contact our billing desk with your registered account email and transaction UTR:
        </p>
        <div className="bg-[#1A1A1A] border border-white/10 rounded-xl p-4 text-xs space-y-1 text-white/80">
          <p><strong>Billing Desk:</strong> billing@brandvox.ai / support@brandvox.ai</p>
          <p><strong>Turnaround Time:</strong> Review within 24–48 business hours</p>
          <p><strong>Refund Method:</strong> Original source UPI ID or bank account</p>
        </div>
      </section>
    </LegalLayout>
  );
}
