// client/src/pages/legal/TermsOfService.jsx
import React from 'react';
import LegalLayout from './LegalLayout';

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="October 2026">
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">1. Agreement to Terms</h2>
        <p>
          These Terms of Service ("Terms") constitute a legally binding agreement between you and BrandVox AI ("BrandVox", "we", "us", or "our") regarding your access to and use of the BrandVox AI software application, website, and generative media synthesis services. By creating an account or accessing our services, you expressly agree to be bound by these Terms.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">2. Eligibility & Accounts</h2>
        <p>
          You must be at least 18 years of age or the age of legal majority in your jurisdiction to create an account. You are responsible for safeguarding your credentials and are solely liable for all activity conducted through your authenticated account.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">3. Acceptable Use Policy & Prohibited Conduct</h2>
        <p>
          BrandVox AI strictly prohibits using our generative artificial intelligence tools for harmful, unlawful, or abusive purposes. You expressly agree that you will not submit prompts or upload media to synthesize:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-white/70">
          <li><strong>Child Exploitation:</strong> Any child sexual abuse material (CSAM) or content exploiting minors. Violations are reported to law enforcement authorities without notice.</li>
          <li><strong>Non-Consensual Synthetic Media (Deepfakes):</strong> Creating intimate, defamatory, or deceptive synthetic media using the likeness or voice of real persons without their affirmative legal consent.</li>
          <li><strong>Harassment & Hate Speech:</strong> Content promoting violence, hatred, discrimination, or severe harassment against individuals or protected groups.</li>
          <li><strong>Intellectual Property Infringement:</strong> Content that knowingly infringes third-party patents, copyrights, trademarks, or proprietary trade secrets.</li>
          <li><strong>Malicious Code & Security Probing:</strong> Circumventing platform rate limits, scraping, reverse engineering, or exploiting server APIs.</li>
        </ul>
        <p className="text-xs text-red-400 font-semibold">
          Violation of this section results in immediate and permanent account termination, forfeiture of unused credits, and potential referral to regulatory or law enforcement agencies.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">4. Likeness Rights & User Warranties for Character Swap</h2>
        <p>
          When utilizing our Character Motion Transfer or Image-to-Video features, you represent and warrant that you hold all necessary legal rights, licenses, or explicit consent from any living individual whose photograph, face, or likeness is uploaded to our platform. You agree to defend, indemnify, and hold harmless BrandVox AI from any third-party claims asserting privacy, publicity, or defamation violations arising from your uploaded media.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">5. Commercial Rights & Output Ownership</h2>
        <p>
          Subject to your full compliance with these Terms and payment of applicable credits, you own all rights, title, and commercial exploitation interests in the AI videos and images generated by your account, to the fullest extent permitted by law and subject to the underlying terms of foundation model providers (such as Fal.ai, Kling, ByteDance, and MiniMax).
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">6. Credits, Top-Ups & Pricing</h2>
        <p>
          BrandVox AI operates on a pay-as-you-go credit ledger denominated in Indian Rupees (INR). Credits are consumed per-second or per-generation based on the active model pricing schedule. Credit top-ups are non-transferable. If an AI generation fails due to an internal system fault or GPU provider interruption, the exact credit amount deducted is automatically refunded back to your account balance.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">7. Disclaimer of Warranties & Limitation of Liability</h2>
        <p>
          The service is provided on an "AS IS" and "AS AVAILABLE" basis. While we partner with state-of-the-art neural network providers, we do not guarantee that generation results will be error-free or meet subjective artistic expectations. In no event shall BrandVox AI be liable for indirect, punitive, or consequential damages.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-xl font-bold text-white">8. Governing Law & Dispute Resolution</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws of India. Any disputes arising from or relating to these Terms shall be subject to the exclusive jurisdiction of the competent courts in India.
        </p>
      </section>
    </LegalLayout>
  );
}
